// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class argType{
    public String arg;
    public exprType annotation;
    public int lineno;
    public int col_offset;

    public argType(String arg, exprType annotation,int lineno, int
    col_offset) {
        this.arg = arg;
        this.annotation = annotation;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "argType";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        traverse(visitor);
        return null;
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
