// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class argumentsType extends PythonNode {
    public argType[] args;
    public argType vararg;
    public argType[] kwonlyargs;
    public exprType[] kw_defaults;
    public argType kwarg;
    public exprType[] defaults;

    public argumentsType(argType[] args, argType vararg, argType[]
    kwonlyargs, exprType[] kw_defaults, argType kwarg, exprType[] defaults)
    {
        this.args = args;
        this.vararg = vararg;
        this.kwonlyargs = kwonlyargs;
        this.kw_defaults = kw_defaults;
        this.kwarg = kwarg;
        this.defaults = defaults;
    }

    public argumentsType(argType[] args, argType vararg, argType[]
    kwonlyargs, exprType[] kw_defaults, argType kwarg, exprType[] defaults,
    PythonNode parent) {
        this(args, vararg, kwonlyargs, kw_defaults, kwarg, defaults);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "argumentsType";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        traverse(visitor);
        return null;
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
