// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class argumentsType{
    public java.util.List<argType> args;
    public argType vararg;
    public java.util.List<argType> kwonlyargs;
    public java.util.List<exprType> kw_defaults;
    public argType kwarg;
    public java.util.List<exprType> defaults;

    public argumentsType(java.util.List<argType> args, argType vararg,
    java.util.List<argType> kwonlyargs, java.util.List<exprType>
    kw_defaults, argType kwarg, java.util.List<exprType> defaults) {
        this.args = args;
        this.vararg = vararg;
        this.kwonlyargs = kwonlyargs;
        this.kw_defaults = kw_defaults;
        this.kwarg = kwarg;
        this.defaults = defaults;
    }

    public String toString() {
        return "argumentsType";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        traverse(visitor);
        return null;
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
