// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class AsyncWith extends stmtType {
    public withitemType[] items;
    public stmtType[] body;

    public AsyncWith(withitemType[] items, stmtType[] body) {
        this.items = items;
        this.body = body;
    }

    public AsyncWith(withitemType[] items, stmtType[] body, PythonNode
    parent) {
        this(items, body);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "AsyncWith";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitAsyncWith(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
