// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class AugAssign extends stmtType {
    public exprType target;
    public operatorType op;
    public exprType value;

    public AugAssign(exprType target, operatorType op, exprType value,int
    lineno, int col_offset) {
        this.target = target;
        this.op = op;
        this.value = value;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "AugAssign";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitAugAssign(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
