// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class BoolOp extends exprType {
    public boolopType op;
    public java.util.List<exprType> values;

    public BoolOp(boolopType op, java.util.List<exprType> values,int
    lineno, int col_offset) {
        this.op = op;
        this.values = values;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "BoolOp";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitBoolOp(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
