// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class Bytes extends exprType {
    public byte[] s;

    public Bytes(byte[] s) {
        this.s = s;
    }

    public Bytes(byte[] s, PythonNode parent) {
        this(s);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "Bytes";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitBytes(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
