// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Bytes extends exprType {
    public PyObject s;

    public Bytes(PyObject s,int lineno, int col_offset) {
        this.s = s;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Bytes";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitBytes(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
