// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class ClassDef extends stmtType {
    public String name;
    public exprType[] bases;
    public keywordType[] keywords;
    public stmtType[] body;
    public exprType[] decorator_list;

    public ClassDef(String name, exprType[] bases, keywordType[] keywords,
    stmtType[] body, exprType[] decorator_list) {
        this.name = name;
        this.bases = bases;
        this.keywords = keywords;
        this.body = body;
        this.decorator_list = decorator_list;
    }

    public ClassDef(String name, exprType[] bases, keywordType[] keywords,
    stmtType[] body, exprType[] decorator_list, PythonNode parent) {
        this(name, bases, keywords, body, decorator_list);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "ClassDef";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitClassDef(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
