// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class ClassDef extends stmtType {
    public String name;
    public java.util.List<exprType> bases;
    public java.util.List<keywordType> keywords;
    public java.util.List<stmtType> body;
    public java.util.List<exprType> decorator_list;

    public ClassDef(String name, java.util.List<exprType> bases,
    java.util.List<keywordType> keywords, java.util.List<stmtType> body,
    java.util.List<exprType> decorator_list,int lineno, int col_offset) {
        this.name = name;
        this.bases = bases;
        this.keywords = keywords;
        this.body = body;
        this.decorator_list = decorator_list;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "ClassDef";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitClassDef(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
