// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class comprehensionType extends PythonNode {
    public exprType target;
    public exprType iter;
    public exprType[] ifs;

    public comprehensionType(exprType target, exprType iter, exprType[]
    ifs) {
        this.target = target;
        this.iter = iter;
        this.ifs = ifs;
    }

    public comprehensionType(exprType target, exprType iter, exprType[]
    ifs, PythonNode parent) {
        this(target, iter, ifs);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "comprehensionType";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        traverse(visitor);
        return null;
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
