// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Compare extends exprType {
    public exprType left;
    public java.util.List<cmpopType> ops;
    public java.util.List<exprType> comparators;

    public Compare(exprType left, java.util.List<cmpopType> ops,
    java.util.List<exprType> comparators,int lineno, int col_offset) {
        this.left = left;
        this.ops = ops;
        this.comparators = comparators;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Compare";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitCompare(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
