// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Delete extends stmtType {
    public java.util.List<exprType> targets;

    public Delete(java.util.List<exprType> targets,int lineno, int
    col_offset) {
        this.targets = targets;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Delete";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitDelete(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
