// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Dict extends exprType {
    public java.util.List<exprType> keys;
    public java.util.List<exprType> values;

    public Dict(java.util.List<exprType> keys, java.util.List<exprType>
    values,int lineno, int col_offset) {
        this.keys = keys;
        this.values = values;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Dict";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitDict(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
