// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class DictComp extends exprType {
    public exprType key;
    public exprType value;
    public java.util.List<comprehensionType> generators;

    public DictComp(exprType key, exprType value,
    java.util.List<comprehensionType> generators,int lineno, int
    col_offset) {
        this.key = key;
        this.value = value;
        this.generators = generators;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "DictComp";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitDictComp(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
