// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class ExceptHandler extends excepthandlerType {
    public exprType type;
    public String name;
    public stmtType[] body;

    public ExceptHandler(exprType type, String name, stmtType[] body) {
        this.type = type;
        this.name = name;
        this.body = body;
    }

    public ExceptHandler(exprType type, String name, stmtType[] body,
    PythonNode parent) {
        this(type, name, body);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "ExceptHandler";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitExceptHandler(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
