// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;

public enum expr_contextType {
    UNDEFINED,
    Load,
    Store,
    Del,
    AugLoad,
    AugStore,
    Param,
}
