// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class Expr extends stmtType {
    public exprType value;

    public Expr(exprType value) {
        this.value = value;
    }

    public Expr(exprType value, PythonNode parent) {
        this(value);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "Expr";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitExpr(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
