// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class ExtSlice extends sliceType {
    public java.util.List<sliceType> dims;

    public ExtSlice(java.util.List<sliceType> dims) {
        this.dims = dims;
    }

    public String toString() {
        return "ExtSlice";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitExtSlice(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
