// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class For extends stmtType {
    public exprType target;
    public exprType iter;
    public java.util.List<stmtType> body;
    public java.util.List<stmtType> orelse;

    public For(exprType target, exprType iter, java.util.List<stmtType>
    body, java.util.List<stmtType> orelse,int lineno, int col_offset) {
        this.target = target;
        this.iter = iter;
        this.body = body;
        this.orelse = orelse;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "For";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitFor(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
