// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class FunctionDef extends stmtType {
    public String name;
    public argumentsType args;
    public java.util.List<stmtType> body;
    public java.util.List<exprType> decorator_list;
    public exprType returns;

    public FunctionDef(String name, argumentsType args,
    java.util.List<stmtType> body, java.util.List<exprType> decorator_list,
    exprType returns,int lineno, int col_offset) {
        this.name = name;
        this.args = args;
        this.body = body;
        this.decorator_list = decorator_list;
        this.returns = returns;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "FunctionDef";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitFunctionDef(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
