// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Global extends stmtType {
    public java.util.List<String> names;

    public Global(java.util.List<String> names,int lineno, int col_offset) {
        this.names = names;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Global";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitGlobal(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
