// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class ImportFrom extends stmtType {
    public String module;
    public java.util.List<aliasType> names;
    public int level;

    public ImportFrom(String module, java.util.List<aliasType> names, int
    level,int lineno, int col_offset) {
        this.module = module;
        this.names = names;
        this.level = level;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "ImportFrom";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitImportFrom(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
