// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class ImportFrom extends stmtType {
    public String module;
    public aliasType[] names;
    public int level;

    public ImportFrom(String module, aliasType[] names, int level) {
        this.module = module;
        this.names = names;
        this.level = level;
    }

    public ImportFrom(String module, aliasType[] names, int level,
    PythonNode parent) {
        this(module, names, level);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "ImportFrom";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitImportFrom(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
