// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Interactive extends modType {
    public java.util.List<stmtType> body;

    public Interactive(java.util.List<stmtType> body) {
        this.body = body;
    }

    public String toString() {
        return "Interactive";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitInteractive(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
