// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class NameConstant extends exprType {
    public PyObject value;

    public NameConstant(PyObject value) {
        this.value = value;
    }

    public NameConstant(PyObject value, PythonNode parent) {
        this(value);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "NameConstant";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitNameConstant(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
