// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Num extends exprType {
    public PyObject n;

    public Num(PyObject n,int lineno, int col_offset) {
        this.n = n;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Num";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitNum(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
