// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Raise extends stmtType {
    public exprType exc;
    public exprType cause;

    public Raise(exprType exc, exprType cause,int lineno, int col_offset) {
        this.exc = exc;
        this.cause = cause;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Raise";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitRaise(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
