// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class Raise extends stmtType {
    public exprType exc;
    public exprType cause;

    public Raise(exprType exc, exprType cause) {
        this.exc = exc;
        this.cause = cause;
    }

    public Raise(exprType exc, exprType cause, PythonNode parent) {
        this(exc, cause);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "Raise";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitRaise(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
