// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Set extends exprType {
    public java.util.List<exprType> elts;

    public Set(java.util.List<exprType> elts,int lineno, int col_offset) {
        this.elts = elts;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Set";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitSet(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
