// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class Set extends exprType {
    public exprType[] elts;

    public Set(exprType[] elts) {
        this.elts = elts;
    }

    public Set(exprType[] elts, PythonNode parent) {
        this(elts);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "Set";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitSet(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
