// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class SetComp extends exprType {
    public exprType elt;
    public java.util.List<comprehensionType> generators;

    public SetComp(exprType elt, java.util.List<comprehensionType>
    generators,int lineno, int col_offset) {
        this.elt = elt;
        this.generators = generators;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "SetComp";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitSetComp(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
