// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Starred extends exprType {
    public exprType value;
    public expr_contextType ctx;

    public Starred(exprType value, expr_contextType ctx,int lineno, int
    col_offset) {
        this.value = value;
        this.ctx = ctx;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Starred";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitStarred(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
