// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import pers.xia.jpython.parser.PythonNode;
import java.io.DataOutputStream;
import java.io.IOException;

public class Try extends stmtType {
    public stmtType[] body;
    public excepthandlerType[] handlers;
    public stmtType[] orelse;
    public stmtType[] finalbody;

    public Try(stmtType[] body, excepthandlerType[] handlers, stmtType[]
    orelse, stmtType[] finalbody) {
        this.body = body;
        this.handlers = handlers;
        this.orelse = orelse;
        this.finalbody = finalbody;
    }

    public Try(stmtType[] body, excepthandlerType[] handlers, stmtType[]
    orelse, stmtType[] finalbody, PythonNode parent) {
        this(body, handlers, orelse, finalbody);
        this.beginLine = parent.beginLine;
        this.beginColumn = parent.beginColumn;
    }

    public String toString() {
        return "Try";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitTry(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
