// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class Try extends stmtType {
    public java.util.List<stmtType> body;
    public java.util.List<excepthandlerType> handlers;
    public java.util.List<stmtType> orelse;
    public java.util.List<stmtType> finalbody;

    public Try(java.util.List<stmtType> body,
    java.util.List<excepthandlerType> handlers, java.util.List<stmtType>
    orelse, java.util.List<stmtType> finalbody,int lineno, int col_offset) {
        this.body = body;
        this.handlers = handlers;
        this.orelse = orelse;
        this.finalbody = finalbody;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Try";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitTry(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
