// Autogenerated AST node
package pers.xia.jpython.ast;
import pers.xia.jpython.object.PyObject;
import java.io.DataOutputStream;
import java.io.IOException;

public class With extends stmtType {
    public java.util.List<withitemType> items;
    public java.util.List<stmtType> body;

    public With(java.util.List<withitemType> items,
    java.util.List<stmtType> body,int lineno, int col_offset) {
        this.items = items;
        this.body = body;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "With";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitWith(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
